import type { Ferry } from "./types"

export const ferries: Ferry[] = [
  {
    id: "FC-101",
    name: "한려호",
    route: { from: "여수", to: "통영" },
    departure: "08:00",
    arrival: "10:30",
    status: "departed",
    capacity: 250,
    boarded: 250,
    platform: "1번",
  },
  {
    id: "FC-102",
    name: "남해누리",
    route: { from: "여수", to: "제주" },
    departure: "09:30",
    arrival: "13:00",
    status: "boarding",
    capacity: 400,
    boarded: 312,
    platform: "2번",
  },
  {
    id: "FC-103",
    name: "돌산도",
    route: { from: "여수", to: "거문도" },
    departure: "10:00",
    arrival: "12:00",
    status: "on-time",
    capacity: 150,
    boarded: 88,
    platform: "3번",
  },
  {
    id: "FC-104",
    name: "오동도",
    route: { from: "여수", to: "낙도" },
    departure: "11:30",
    arrival: "13:00",
    status: "delayed",
    capacity: 120,
    boarded: 45,
    platform: "4번",
  },
  {
    id: "FC-105",
    name: "금오도",
    route: { from: "여수", to: "금오도" },
    departure: "13:00",
    arrival: "14:00",
    status: "on-time",
    capacity: 180,
    boarded: 0,
    platform: "1번",
  },
  {
    id: "FC-106",
    name: "백야호",
    route: { from: "여수", to: "백야도" },
    departure: "14:00",
    arrival: "15:30",
    status: "cancelled",
    capacity: 100,
    boarded: 0,
    platform: "-",
  },
]
