import type { Ferry } from "./types"

export const wandoFerries: Ferry[] = [
  {
    id: "WD-201",
    name: "한일카페리",
    route: { from: "제주", to: "완도" },
    departure: "07:00",
    arrival: "10:00",
    status: "departed",
    capacity: 450,
    boarded: 420,
    platform: "2번",
  },
  {
    id: "WD-202",
    name: "씨스타크루즈",
    route: { from: "제주", to: "완도" },
    departure: "09:30",
    arrival: "12:30",
    status: "on-time",
    capacity: 300,
    boarded: 180,
    platform: "1번",
  },
  {
    id: "WD-203",
    name: "청산페리",
    route: { from: "청산도", to: "완도" },
    departure: "10:00",
    arrival: "10:50",
    status: "boarding",
    capacity: 100,
    boarded: 85,
    platform: "3번",
  },
  {
    id: "WD-204",
    name: "보길누리",
    route: { from: "보길도", to: "완도" },
    departure: "11:00",
    arrival: "12:00",
    status: "delayed",
    capacity: 80,
    boarded: 30,
    platform: "4번",
  },
  {
    id: "WD-205",
    name: "소안도호",
    route: { from: "소안도", to: "완도" },
    departure: "13:30",
    arrival: "14:30",
    status: "on-time",
    capacity: 60,
    boarded: 0,
    platform: "2번",
  },
  {
    id: "WD-206",
    name: "노화도호",
    route: { from: "노화도", to: "완도" },
    departure: "15:00",
    arrival: "15:40",
    status: "cancelled",
    capacity: 70,
    boarded: 0,
    platform: "-",
  },
]

export const ferries: Ferry[] = [
  {
    id: "WD-D01",
    name: "한일카페리",
    route: { from: "완도", to: "제주" },
    departure: "08:00",
    arrival: "11:00",
    status: "departed",
    capacity: 450,
    boarded: 430,
    platform: "1번",
  },
  {
    id: "WD-D02",
    name: "청산페리",
    route: { from: "완도", to: "청산도" },
    departure: "09:00",
    arrival: "09:50",
    status: "boarding",
    capacity: 100,
    boarded: 72,
    platform: "3번",
  },
  {
    id: "WD-D03",
    name: "보길누리",
    route: { from: "완도", to: "보길도" },
    departure: "10:30",
    arrival: "11:30",
    status: "on-time",
    capacity: 80,
    boarded: 45,
    platform: "4번",
  },
  {
    id: "WD-D04",
    name: "소안도호",
    route: { from: "완도", to: "소안도" },
    departure: "12:00",
    arrival: "13:00",
    status: "delayed",
    capacity: 60,
    boarded: 28,
    platform: "2번",
  },
  {
    id: "WD-D05",
    name: "노화도호",
    route: { from: "완도", to: "노화도" },
    departure: "14:00",
    arrival: "14:40",
    status: "on-time",
    capacity: 70,
    boarded: 0,
    platform: "3번",
  },
  {
    id: "WD-D06",
    name: "넙도페리",
    route: { from: "완도", to: "넙도" },
    departure: "15:30",
    arrival: "16:20",
    status: "cancelled",
    capacity: 50,
    boarded: 0,
    platform: "-",
  },
]
