import type { Ferry } from "./types"

export const wandoFerries: Ferry[] = [
  {
    id: "WD-201",
    name: "한일카페리",
    route: { from: "제주", to: "완도" },
    departure: "07:00",
    arrival: "10:00",
    status: "departed",
    capacity: 450,
    boarded: 420,
    platform: "2번",
  },
  {
    id: "WD-202",
    name: "씨스타크루즈",
    route: { from: "제주", to: "완도" },
    departure: "09:30",
    arrival: "12:30",
    status: "on-time",
    capacity: 300,
    boarded: 180,
    platform: "1번",
  },
  {
    id: "WD-203",
    name: "청산페리",
    route: { from: "청산도", to: "완도" },
    departure: "10:00",
    arrival: "10:50",
    status: "boarding",
    capacity: 100,
    boarded: 85,
    platform: "3번",
  },
  {
    id: "WD-204",
    name: "보길누리",
    route: { from: "보길도", to: "완도" },
    departure: "11:00",
    arrival: "12:00",
    status: "delayed",
    capacity: 80,
    boarded: 30,
    platform: "4번",
  },
  {
    id: "WD-205",
    name: "소안도호",
    route: { from: "소안도", to: "완도" },
    departure: "13:30",
    arrival: "14:30",
    status: "on-time",
    capacity: 60,
    boarded: 0,
    platform: "2번",
  },
  {
    id: "WD-206",
    name: "노화도호",
    route: { from: "노화도", to: "완도" },
    departure: "15:00",
    arrival: "15:40",
    status: "cancelled",
    capacity: 70,
    boarded: 0,
    platform: "-",
  },
]

export const ferries: Ferry[] = [
  {
    id: "FC-101",
    name: "한려호",
    route: { from: "여수", to: "통영" },
    departure: "08:00",
    arrival: "10:30",
    status: "departed",
    capacity: 250,
    boarded: 250,
    platform: "1번",
  },
  {
    id: "FC-102",
    name: "남해누리",
    route: { from: "여수", to: "제주" },
    departure: "09:30",
    arrival: "13:00",
    status: "boarding",
    capacity: 400,
    boarded: 312,
    platform: "2번",
  },
  {
    id: "FC-103",
    name: "돌산도",
    route: { from: "여수", to: "거문도" },
    departure: "10:00",
    arrival: "12:00",
    status: "on-time",
    capacity: 150,
    boarded: 88,
    platform: "3번",
  },
  {
    id: "FC-104",
    name: "오동도",
    route: { from: "여수", to: "낙도" },
    departure: "11:30",
    arrival: "13:00",
    status: "delayed",
    capacity: 120,
    boarded: 45,
    platform: "4번",
  },
  {
    id: "FC-105",
    name: "금오도",
    route: { from: "여수", to: "금오도" },
    departure: "13:00",
    arrival: "14:00",
    status: "on-time",
    capacity: 180,
    boarded: 0,
    platform: "1번",
  },
  {
    id: "FC-106",
    name: "백야호",
    route: { from: "여수", to: "백야도" },
    departure: "14:00",
    arrival: "15:30",
    status: "cancelled",
    capacity: 100,
    boarded: 0,
    platform: "-",
  },
]
