export type TourPlace = {
  name: string
  category: string
  description: string
  mapQuery: string
  officialHref: string
}

export type TourGuide = {
  slug: string
  region: string
  title: string
  description: string
  arrivalPort: string
  intro: string
  sourceNote: string
  updated: string
  sourceLabel: string
  officialHref: string
  ferryGuideHref: string
  ferryGuideLabel: string
  places: TourPlace[]
}

// 관광지 설명은 완도문화관광이 안내한 명칭과 범위만 정리한다.
// 운영시간·요금·교통편처럼 수시로 달라지는 정보는 이 목록에 고정하지 않는다.
export const TOUR_GUIDES: TourGuide[] = [
  {
    slug: "cheongsando",
    region: "청산도",
    title: "청산도 주요 관광지 — 도청항에서 확인하는 5곳",
    description: "청산도 도청항에 도착한 뒤 찾아볼 수 있는 서편제 촬영지, 봄의 왈츠 촬영지, 범바위, 상서마을 옛담장, 신흥리해수욕장을 공식 관광 안내 기준으로 정리했습니다.",
    arrivalPort: "도청항",
    intro: "청산도행 여객선은 도청항을 기준으로 도착합니다. 아래 장소는 완도문화관광이 청산권 주요 관광지로 소개한 곳입니다. 섬 안 이동 시간, 운영 여부, 주차·입장 조건은 방문일에 공식 안내 또는 현지 운영처에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 완도문화관광의 청산도·청산권 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 공식 안내를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "완도문화관광",
    officialHref: "https://www.wando.go.kr/tour/sub.cs?m=106",
    ferryGuideHref: "/guide/wando-cheongsando",
    ferryGuideLabel: "청산도 배편·승선 안내 보기",
    places: [
      {
        name: "서편제 촬영지",
        category: "촬영지 · 슬로길 풍경",
        description: "영화 ‘서편제’의 장면이 촬영된 곳으로, 황토길과 주변 풍경을 함께 볼 수 있는 청산도의 대표 촬영지입니다.",
        mapQuery: "청산도 서편제 촬영지",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=106",
      },
      {
        name: "봄의 왈츠 촬영지",
        category: "촬영지 · 들판 풍경",
        description: "드라마 ‘봄의 왈츠’ 촬영지로 소개된 장소입니다. 바닷가 언덕의 오픈세트장과 주변 돌담길 풍경을 함께 볼 수 있습니다.",
        mapQuery: "청산도 봄의 왈츠 촬영지",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=106",
      },
      {
        name: "범바위",
        category: "자연 경관",
        description: "완도문화관광이 청산권 주요 관광지로 안내하는 바위 경관입니다. 이동·탐방 여건은 날씨와 현장 안내를 먼저 확인하세요.",
        mapQuery: "청산도 범바위",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=17&startPage=1&tCimThemeAreaCode=Z004",
      },
      {
        name: "상서마을 옛담장",
        category: "마을 · 돌담길",
        description: "상서리와 동촌리를 지나는 돌담 풍경으로 소개되는 마을 길입니다. 생활 공간이므로 주민과 차량 통행에 유의해 둘러보세요.",
        mapQuery: "청산도 상서마을 옛담장",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=106",
      },
      {
        name: "신흥리해수욕장",
        category: "해변",
        description: "완도문화관광이 청산권 주요 관광지로 안내하는 해변입니다. 개장·안전요원·편의시설 운영 여부는 계절과 방문일에 따라 확인하세요.",
        mapQuery: "청산도 신흥리해수욕장",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=17&startPage=1&tCimThemeAreaCode=Z004",
      },
    ],
  },
  {
    slug: "bogildo",
    region: "보길도",
    title: "보길도 주요 관광지 — 동천항에서 이어지는 4곳",
    description: "동천항에 도착한 뒤 보길대교를 건너 찾아볼 수 있는 보길도 윤선도 원림, 예송리해수욕장, 통리해수욕장, 망끝전망대를 완도문화관광 안내 기준으로 정리했습니다.",
    arrivalPort: "동천항",
    intro: "화흥포항 출발편은 노화도 동천항에 도착합니다. 보길도는 동천항에서 보길대교를 건너 이동합니다. 아래 장소는 완도문화관광의 보길도 당일코스에 소개된 곳이며, 섬 안 이동 시간과 운영 여부는 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 완도문화관광의 보길도 당일코스와 보길도 윤선도 원림 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 공식 안내를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "완도문화관광",
    officialHref: "https://www.wando.go.kr/tour/sub.cs?m=105",
    ferryGuideHref: "/guide/wando-soan-bogil-nohwa",
    ferryGuideLabel: "화흥포·보길도 배편·승선 안내 보기",
    places: [
      {
        name: "보길도 윤선도 원림",
        category: "역사 · 정원",
        description: "고산 윤선도의 생활·창작 공간으로 소개되는 부용동 정원입니다. 낙서재, 세연정, 동천석실 등으로 이어지는 조선시대 별서정원의 구성을 볼 수 있습니다.",
        mapQuery: "보길도 윤선도 원림",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=30",
      },
      {
        name: "예송리해수욕장",
        category: "해변 · 상록수림",
        description: "완도문화관광 보길도 코스에 소개된 해변입니다. 해변 뒤편의 상록수림과 주변 섬 풍경을 함께 볼 수 있는 곳으로 안내됩니다.",
        mapQuery: "보길도 예송리해수욕장",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=105",
      },
      {
        name: "통리해수욕장",
        category: "해변 · 바다 풍경",
        description: "보길도 당일코스에 포함된 해변입니다. 앞바다의 여러 섬과 해변 풍경을 볼 수 있는 장소로 소개됩니다.",
        mapQuery: "보길도 통리해수욕장",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=105",
      },
      {
        name: "망끝전망대",
        category: "전망 · 해안 경관",
        description: "보길도 서쪽 망월봉 끝자락에 자리한 전망대입니다. 다도해 섬과 바다를 조망하는 장소로 완도문화관광이 안내합니다.",
        mapQuery: "보길도 망끝전망대",
        officialHref: "https://www.wando.go.kr/tour/sub.cs?m=105",
      },
    ],
  },
  {
    slug: "hongdo",
    region: "홍도",
    title: "홍도 주요 관광지 — 홍도항 도착 뒤 확인하는 3곳",
    description: "홍도항에 도착한 뒤 찾아볼 수 있는 홍도 해상관광, 깃대봉, 홍도 전망대를 한국관광공사 안내 기준으로 정리했습니다.",
    arrivalPort: "홍도항",
    intro: "목포 출발편은 홍도항에 도착합니다. 홍도는 섬 전체가 천연보호구역으로 지정된 지역입니다. 아래 장소는 한국관광공사 안내에 소개된 곳이며, 탐방·유람선 운영 여부와 현장 규정은 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 한국관광공사 대한민국 구석구석의 홍도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "한국관광공사 홍도 공식 안내",
    officialHref: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=857fd91d-1c56-4581-8631-edd47e6bd318",
    ferryGuideHref: "/guide/mokpo-hongdo",
    ferryGuideLabel: "목포·홍도 배편·승선 안내 보기",
    places: [
      {
        name: "홍도 해상관광",
        category: "유람선 · 해안 경관",
        description: "홍도의 해안 절벽과 주변 섬 풍경을 배 위에서 보는 관광 방식입니다. 운항 여부와 승선 조건은 해상 상황 및 현지 유람선 안내를 확인하세요.",
        mapQuery: "홍도 유람선 관광",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=f6f1db28-c2a3-42b5-bca7-95e393130ef2",
      },
      {
        name: "깃대봉",
        category: "탐방 · 정상 경관",
        description: "홍도의 주봉으로 소개되는 곳입니다. 정상에서는 주변 능선과 섬 풍경을 볼 수 있으며, 탐방 전 날씨와 현장 통제 여부를 확인하는 것이 좋습니다.",
        mapQuery: "홍도 깃대봉",
        officialHref: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=857fd91d-1c56-4581-8631-edd47e6bd318",
      },
      {
        name: "홍도 전망대",
        category: "전망 · 섬 풍경",
        description: "한국관광공사 홍도 안내에서 깃대봉 탐방로와 함께 소개된 전망 장소입니다. 이동 여건과 이용 가능 구간은 현지 안내를 확인하세요.",
        mapQuery: "홍도 전망대",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=f6f1db28-c2a3-42b5-bca7-95e393130ef2",
      },
    ],
  },
  {
    slug: "heuksando",
    region: "흑산도",
    title: "흑산도 주요 관광지 — 흑산도항 도착 뒤 확인하는 4곳",
    description: "흑산도항에 도착한 뒤 찾아볼 수 있는 흑산도 일주도로, 상라봉 전망대, 자산문화원, 배낭기미해수욕장을 한국관광공사 안내 기준으로 정리했습니다.",
    arrivalPort: "흑산도항",
    intro: "목포 출발편은 흑산도항에 도착합니다. 흑산도 안 관광지는 항구에서 떨어진 곳도 있어 섬 안 이동을 따로 계획하는 편이 좋습니다. 아래 장소는 한국관광공사 안내에 소개된 곳이며, 도로·탐방 여건과 운영 여부는 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 한국관광공사 대한민국 구석구석의 흑산도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "한국관광공사 흑산도 공식 안내",
    officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7acc69af-7a3b-47d9-9ddc-1c22a358ae28",
    ferryGuideHref: "/guide/mokpo-heuksando",
    ferryGuideLabel: "목포·흑산도 배편·승선 안내 보기",
    places: [
      {
        name: "흑산도 일주도로",
        category: "드라이브 · 해안 경관",
        description: "해안을 따라 섬을 둘러볼 수 있는 도로입니다. 전망 장소와 굽이진 구간이 이어져 있어 이동 수단과 당일 도로 여건을 먼저 확인하는 것이 좋습니다.",
        mapQuery: "흑산도 일주도로",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7acc69af-7a3b-47d9-9ddc-1c22a358ae28",
      },
      {
        name: "상라봉 전망대",
        category: "전망 · 섬 풍경",
        description: "상라산 일대의 전망 장소로 소개됩니다. 흑산도항과 주변 섬 풍경을 볼 수 있으며, 탐방 전 날씨와 현장 통제 여부를 확인하세요.",
        mapQuery: "흑산도 상라봉 전망대",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7acc69af-7a3b-47d9-9ddc-1c22a358ae28",
      },
      {
        name: "자산문화원",
        category: "문화 · 자산어보",
        description: "정약전의 흑산도 유배 생활과 『자산어보』 관련 자료를 소개하는 곳으로 안내됩니다. 전시 운영 여부는 방문 전에 확인하세요.",
        mapQuery: "흑산도 자산문화원",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7acc69af-7a3b-47d9-9ddc-1c22a358ae28",
      },
      {
        name: "배낭기미해수욕장",
        category: "해변 · 휴식",
        description: "한국관광공사 흑산도 안내에서 대표 해수욕장으로 소개된 곳입니다. 계절별 개장·안전·편의시설 운영 여부는 현지 안내를 확인하세요.",
        mapQuery: "흑산도 배낭기미해수욕장",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7acc69af-7a3b-47d9-9ddc-1c22a358ae28",
      },
    ],
  },
  {
    slug: "gageodo",
    region: "가거도",
    title: "가거도 주요 관광지 — 가거도항 도착 뒤 확인하는 4곳",
    description: "가거도항에 도착한 뒤 찾아볼 수 있는 독실산, 섬등반도, 가거도 등대, 회룡산을 한국관광공사 안내 기준으로 정리했습니다.",
    arrivalPort: "가거도항",
    intro: "목포 출발편은 가거도항에 도착합니다. 가거도는 산지와 해안 절벽 지형이 이어져 섬 안 이동을 별도로 계획해야 합니다. 아래 장소는 한국관광공사 안내에 소개된 곳이며, 탐방로·도로·운영 여건은 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 한국관광공사 대한민국 구석구석의 가거도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "한국관광공사 가거도 공식 안내",
    officialHref: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=47836660-7194-498c-90a6-f8bfa9662b3c",
    ferryGuideHref: "/guide/mokpo-gageodo",
    ferryGuideLabel: "목포·가거도 배편·승선 안내 보기",
    places: [
      {
        name: "독실산",
        category: "탐방 · 산악 경관",
        description: "가거도 중앙에 솟은 산으로 소개됩니다. 날씨 변화와 안개 영향을 받을 수 있어 탐방 전 현지 여건과 안내를 확인하는 것이 좋습니다.",
        mapQuery: "가거도 독실산",
        officialHref: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=47836660-7194-498c-90a6-f8bfa9662b3c",
      },
      {
        name: "섬등반도",
        category: "해안 절벽 · 자연 경관",
        description: "독실산에서 서쪽으로 이어지는 반도형 지형입니다. 주상절리와 해식애가 펼쳐진 해안 경관으로 한국관광공사가 안내합니다.",
        mapQuery: "가거도 섬등반도",
        officialHref: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=47836660-7194-498c-90a6-f8bfa9662b3c",
      },
      {
        name: "가거도 등대",
        category: "등대 · 해안 풍경",
        description: "섬등반도와 함께 가거도 여행 명소로 소개되는 등대입니다. 방문 가능 구간과 이동 여건은 현지 안내를 확인하세요.",
        mapQuery: "가거도 등대",
        officialHref: "https://korean.visitkorea.or.kr/detail/cs_detail_cos.do?cotid=8ba547ce-fc32-45a7-bf9f-203ee1b4a203",
      },
      {
        name: "회룡산",
        category: "전망 · 마을 풍경",
        description: "가거도항과 대리마을 풍경을 볼 수 있는 곳으로 한국관광공사 여행코스에 소개됩니다. 탐방로 상태는 출발 전에 확인하세요.",
        mapQuery: "가거도 회룡산",
        officialHref: "https://korean.visitkorea.or.kr/detail/cs_detail_cos.do?cotid=8ba547ce-fc32-45a7-bf9f-203ee1b4a203",
      },
    ],
  },
  {
    slug: "baengnyeongdo",
    region: "백령도",
    title: "백령도 주요 관광지 — 용기포항 도착 뒤 확인하는 4곳",
    description: "용기포항에 도착한 뒤 찾아볼 수 있는 두무진, 사곶해변, 콩돌해안, 용기원산 전망대를 인천관광·인천시 안내 기준으로 정리했습니다.",
    arrivalPort: "용기포항",
    intro: "인천 출발편은 백령도 용기포항에 도착합니다. 주요 관광지가 섬 안에 흩어져 있어 섬 내 이동을 따로 계획하는 편이 좋습니다. 아래 장소는 인천관광과 인천시 안내에 소개된 곳이며, 기상·통제·운영 여건은 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천관광과 인천광역시 백령·대청 국가지질공원 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천관광 백령도 공식 안내",
    officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21121610281282088&pgListMode=S",
    ferryGuideHref: "/guide/incheon-baengnyeongdo",
    ferryGuideLabel: "인천·백령도 배편·승선 안내 보기",
    places: [
      {
        name: "두무진",
        category: "해안 절벽 · 지질 경관",
        description: "백령도 서북쪽 해안의 기암 절벽 경관입니다. 포구에서 해상관람 또는 육상 탐방으로 볼 수 있으며, 해상관람은 기상에 따라 달라질 수 있습니다.",
        mapQuery: "백령도 두무진",
        officialHref: "https://itour.incheon.go.kr/thmtour/rcmdtour/detail.do?cotId=ITA21121017382163662",
      },
      {
        name: "사곶해변",
        category: "해변 · 지질 명소",
        description: "백령·대청 국가지질공원이 백령도 지질명소로 안내하는 해변입니다. 해변 이용 여건과 안전 안내는 계절·방문일에 따라 확인하세요.",
        mapQuery: "백령도 사곶해변",
        officialHref: "https://www.incheon.go.kr/env/ENV040102",
      },
      {
        name: "콩돌해안",
        category: "해안 · 지질 명소",
        description: "둥글고 작은 자갈이 이어지는 해안으로, 백령·대청 국가지질공원이 안내하는 백령도 지질명소 중 하나입니다.",
        mapQuery: "백령도 콩돌해안",
        officialHref: "https://www.incheon.go.kr/env/ENV040102",
      },
      {
        name: "용기원산 전망대",
        category: "전망 · 섬 전경",
        description: "국토끝섬전망대로도 소개되는 전망 장소입니다. 백령도 전경을 조망할 수 있으며, 이동 전 날씨와 현장 안내를 확인하세요.",
        mapQuery: "백령도 용기원산 전망대",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=db13fe4f-fcf3-45a8-a5c9-146ffe9cec37",
      },
    ],
  },
  {
    slug: "deokjeokdo",
    region: "덕적도",
    title: "덕적도 주요 관광지 — 진리항 도착 뒤 확인하는 4곳",
    description: "진리항에 도착한 뒤 찾아볼 수 있는 비조봉, 서포리해수욕장, 밧지름해변, 도우끝 해안산책로를 인천관광 안내 기준으로 정리했습니다.",
    arrivalPort: "진리항",
    intro: "인천 출발편은 덕적도 진리항에 도착합니다. 관광지와 해변이 섬 안에 흩어져 있어 숙소·교통과 함께 이동 동선을 따로 계획하는 편이 좋습니다. 아래 장소는 인천관광 안내에 소개된 곳이며, 산책·탐방·해변 이용 여건은 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천관광의 덕적도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천관광 덕적도 공식 안내",
    officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012517101819417&pgListMode=S",
    ferryGuideHref: "/guide/incheon-deokjeokdo",
    ferryGuideLabel: "인천·덕적도 배편·승선 안내 보기",
    places: [
      {
        name: "비조봉",
        category: "탐방 · 전망",
        description: "덕적도 남쪽의 봉우리로, 정상에서 서해와 덕적군도 부속 섬을 조망할 수 있는 곳으로 안내됩니다. 산책 수준의 코스가 아니므로 탐방 전 준비와 현장 여건을 확인하세요.",
        mapQuery: "덕적도 비조봉",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122409240921519",
      },
      {
        name: "서포리해수욕장",
        category: "해변 · 소나무숲",
        description: "해변과 소나무숲 산책로가 함께 소개되는 덕적도의 대표 해변입니다. 계절별 개장·안전·편의시설 운영 여부는 현지 안내를 확인하세요.",
        mapQuery: "덕적도 서포리해수욕장",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012517101819417&pgListMode=S",
      },
      {
        name: "밧지름해변",
        category: "해변 · 휴식",
        description: "비조봉 입구와 이어지는 해변으로 소개됩니다. 해변 이용 여건과 이동 가능 구간은 방문일에 확인하세요.",
        mapQuery: "덕적도 밧지름해변",
        officialHref: "https://itour.incheon.go.kr/thmtour/cardnews/detail.do?cotId=CAR24082810171485615",
      },
      {
        name: "도우끝 해안산책로",
        category: "산책 · 해안 풍경",
        description: "진리항 인근에서 해안을 따라 이어지는 산책로입니다. 출발·도착 시간을 고려해 귀항편 전후의 짧은 동선으로 확인하기 좋습니다.",
        mapQuery: "덕적도 도우끝 해안산책로",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=25fbe28a-15c7-42c8-8156-dbecc3ceb51c",
      },
    ],
  },
  {
    slug: "daeijakdo",
    region: "대이작도",
    title: "대이작도 주요 관광지 — 선착장 도착 뒤 확인하는 4곳",
    description: "대이작도에 도착한 뒤 찾아볼 수 있는 풀등, 부아산, 큰풀안·작은풀안해변, 계남일출전망대를 인천관광 안내 기준으로 정리했습니다.",
    arrivalPort: "대이작도 선착장",
    intro: "인천 출발편은 대이작도 선착장에 도착합니다. 풀등은 썰물 때만 드러나는 모래톱이라 방문 시간과 해상 여건을 함께 확인해야 합니다. 아래 장소는 인천관광 안내에 소개된 곳이며, 해변·탐방·현장 프로그램의 운영 여부는 방문일에 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천관광과 인천 섬포털의 대이작도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천관광 대이작도 공식 안내",
    officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012116245038060",
    ferryGuideHref: "/incheon",
    ferryGuideLabel: "인천 배편 시간표 보기",
    places: [
      {
        name: "풀등",
        category: "모래톱 · 해양 생태",
        description: "썰물 때만 모습을 드러내는 해중 모래톱입니다. 바닷물이 차오르면 잠기므로 방문 전 조석·기상과 현지 안내를 반드시 확인하세요.",
        mapQuery: "대이작도 풀등",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122709112053959",
      },
      {
        name: "부아산",
        category: "탐방 · 전망",
        description: "대이작도의 섬과 해변을 조망할 수 있는 산으로 소개됩니다. 부아산 구름다리와 봉수대 주변 이동 여건은 현장 안내를 확인하세요.",
        mapQuery: "대이작도 부아산",
        officialHref: "https://itour.incheon.go.kr/thmtour/thmtour/detail.do?cotId=ITA25082615310498753&pgListMode=S",
      },
      {
        name: "큰풀안·작은풀안해변",
        category: "해변 · 산책",
        description: "대이작도 대표 해변으로 소개되는 곳입니다. 두 해변 사이에는 산책로가 이어지며, 계절별 해변 이용 여건은 현지 안내를 확인하세요.",
        mapQuery: "대이작도 큰풀안해변",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012116245038060",
      },
      {
        name: "계남일출전망대",
        category: "전망 · 해안 풍경",
        description: "인천 섬포털이 대이작도 대표 관광지로 소개하는 전망 장소입니다. 이동 전 도로와 날씨 여건을 확인하세요.",
        mapQuery: "대이작도 계남일출전망대",
        officialHref: "https://isum.incheon.go.kr/isleInfo.do?isle=197&key=2407020009",
      },
    ],
  },
  {
    slug: "gulupdo",
    region: "굴업도",
    title: "굴업도 주요 관광지 — 선착장 도착 뒤 확인하는 4곳",
    description: "굴업도에 도착한 뒤 찾아볼 수 있는 개머리초지, 목기미해변, 굴업리해변, 소굴업도 코끼리바위를 인천 섬포털 안내 기준으로 정리했습니다.",
    arrivalPort: "굴업도 선착장",
    intro: "굴업도는 자연 경관과 캠핑지로 알려진 섬입니다. 섬 안 탐방은 선착장 도착 시각과 귀항편을 먼저 확인해 여유 있게 계획하세요. 해변·초지·해안 탐방의 실제 이동 여건과 현장 운영 정보는 방문일에 확인해야 합니다.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천 섬포털의 굴업도 테마 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천 섬포털 굴업도 공식 안내",
    officialHref: "https://isum.incheon.go.kr/theme/view.do?key=2407020012&themeSn=2409050007&themeType=105",
    ferryGuideHref: "/incheon",
    ferryGuideLabel: "인천 배편 시간표 보기",
    places: [
      {
        name: "개머리초지",
        category: "초지 · 탐방",
        description: "굴업도를 대표하는 넓은 초지로 소개되는 탐방 장소입니다. 야생동물과 자연환경을 훼손하지 않도록 지정된 동선과 현장 안내를 따라 이동하세요.",
        mapQuery: "굴업도 개머리초지",
        officialHref: "https://isum.incheon.go.kr/theme/view.do?key=2407020012&themeSn=2409050007&themeType=105",
      },
      {
        name: "목기미해변",
        category: "해변 · 해안 풍경",
        description: "인천 섬포털이 굴업도 대표 관광지로 소개하는 해변입니다. 해변 이용과 해안 이동은 기상·파고와 현장 안전 여건을 확인하세요.",
        mapQuery: "굴업도 목기미해변",
        officialHref: "https://isum.incheon.go.kr/theme/view.do?key=2407020012&themeSn=2409050007&themeType=105",
      },
      {
        name: "굴업리해변",
        category: "해변 · 산책",
        description: "약 1km 길이의 모래 해변과 해안사구 풍경으로 소개되는 곳입니다. 선착장 귀항 시간을 고려해 해변 산책 동선을 잡는 편이 좋습니다.",
        mapQuery: "굴업도 굴업리해변",
        officialHref: "https://isum.incheon.go.kr/theme/view.do?key=2407020012&themeSn=2409050007&themeType=105",
      },
      {
        name: "소굴업도 코끼리바위",
        category: "해안 지형 · 조망",
        description: "소굴업도 해안의 홍예문 형태 바위로 소개되는 경관입니다. 해상·해안 접근 가능 여부와 안전한 관람 위치는 현지 안내를 확인하세요.",
        mapQuery: "굴업도 소굴업도 코끼리바위",
        officialHref: "https://isum.incheon.go.kr/theme/view.do?key=2407020012&themeSn=2409050007&themeType=105",
      },
    ],
  },
  {
    slug: "yeonpyeongdo",
    region: "연평도",
    title: "연평도 주요 관광지 — 대연평도 도착 뒤 확인하는 4곳",
    description: "연평도에 도착한 뒤 찾아볼 수 있는 연평평화전망대, 조기역사관 전망대, 등대공원, 안보교육장을 인천 관광 안내 기준으로 정리했습니다.",
    arrivalPort: "대연평도 선착장",
    intro: "연평도는 역사·평화·해안 경관을 함께 살필 수 있는 섬입니다. 관광지 운영 여부와 이동 가능 구간은 기상·현장 여건에 따라 달라질 수 있으므로, 출발 전 공식 안내와 현지 안내를 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천 섬포털 및 인천관광의 연평도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천 섬포털 연평도 공식 안내",
    officialHref: "https://isum.incheon.go.kr/isleInfo.do?isle=184&key=2407020005",
    ferryGuideHref: "/incheon",
    ferryGuideLabel: "인천 배편 시간표 보기",
    places: [
      {
        name: "연평평화전망대",
        category: "전망 · 역사",
        description: "전망대와 전시관, 북카페 등이 있는 공간으로 소개됩니다. 관람 가능 시간과 체험 시설 운영 여부는 방문일에 공식 안내를 확인하세요.",
        mapQuery: "연평평화전망대",
        officialHref: "https://isum.incheon.go.kr/spot/view.do?key=2407020020&spotSn=2408010059",
      },
      {
        name: "조기역사관 2층 전망대",
        category: "전시 · 전망",
        description: "연평도의 조기잡이 역사와 풍물을 살펴볼 수 있는 공간으로 소개됩니다. 전시·전망대 이용 가능 시간은 현장 또는 공식 안내를 확인하세요.",
        mapQuery: "연평도 조기역사관",
        officialHref: "https://isum.incheon.go.kr/spot/view.do?key=2407020020&spotSn=2408010060",
      },
      {
        name: "연평도 등대공원",
        category: "공원 · 해안 조망",
        description: "연평도 등대 주변에 조성된 공원입니다. 조기역사관과 가까워 함께 둘러볼 수 있으며, 해안 산책은 날씨와 현장 안전 여건을 확인하세요.",
        mapQuery: "연평도 등대공원",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22012114353636366",
      },
      {
        name: "연평도 안보교육장",
        category: "전시 · 교육",
        description: "연평도 포격도발 현장을 보존해 안보교육의 장으로 운영하는 시설입니다. 관람 전 운영 시간과 입장 가능 여부를 공식 안내에서 확인하세요.",
        mapQuery: "연평도 안보교육장",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122917071069816",
      },
    ],
  },
  {
    slug: "jangbongdo",
    region: "장봉도",
    title: "장봉도 주요 관광지 — 옹암선착장 도착 뒤 확인하는 4곳",
    description: "장봉도에 도착한 뒤 찾아볼 수 있는 옹암해수욕장, 진촌해변, 가막머리낙조대, 장봉도풀등을 인천 섬포털·인천관광 안내 기준으로 정리했습니다.",
    arrivalPort: "장봉도 옹암선착장",
    intro: "장봉도는 삼목항에서 들어가는 가까운 섬이지만, 해변과 산책·전망 장소가 섬 곳곳에 흩어져 있습니다. 선착장 도착 뒤 이동 시간과 삼목항으로 돌아오는 귀항편을 먼저 확인해 일정을 잡으세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 인천 섬포털 및 인천관광의 장봉도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "인천 섬포털 장봉도 공식 안내",
    officialHref: "https://isum.incheon.go.kr/isleInfo.do?isle=179&key=2407020005",
    ferryGuideHref: "/incheon",
    ferryGuideLabel: "인천 배편 시간표 보기",
    places: [
      {
        name: "옹암해수욕장",
        category: "해변 · 산책",
        description: "장봉도 대표 해변으로 소개되는 곳입니다. 해변 이용 가능 구간과 계절별 편의시설 운영 여부는 현장 안내를 확인하세요.",
        mapQuery: "장봉도 옹암해수욕장",
        officialHref: "https://isum.incheon.go.kr/isleInfo.do?isle=179&key=2407020005",
      },
      {
        name: "진촌해변",
        category: "해변 · 휴식",
        description: "장봉도 여행지로 소개되는 해변입니다. 모래 해변 특성상 이동 여건과 해변 이용 가능 여부를 방문일에 확인하세요.",
        mapQuery: "장봉도 진촌해변",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD21122415261761991",
      },
      {
        name: "가막머리낙조대",
        category: "전망 · 산책",
        description: "장봉도 갯티길 종점의 전망 장소로 소개됩니다. 해안 산책은 일몰 전 귀항편과 안전한 복귀 동선을 고려해 계획하세요.",
        mapQuery: "장봉도 가막머리낙조대",
        officialHref: "https://itour.incheon.go.kr/ssst/ssst/detail.do?cotId=ITD22010315032134299",
      },
      {
        name: "장봉도풀등",
        category: "모래톱 · 해양 생태",
        description: "썰물 때 드러나는 모래톱으로 소개됩니다. 물때와 해상 여건에 따라 모습과 접근 가능 여부가 달라지므로 현지 안내를 우선 확인하세요.",
        mapQuery: "장봉도 풀등",
        officialHref: "https://isum.incheon.go.kr/spot/view.do?key=2407020020&spotSn=2407300059",
      },
    ],
  },
  {
    slug: "pungdo",
    region: "풍도",
    title: "풍도 주요 관광지 — 선착장 도착 뒤 확인하는 4곳",
    description: "풍도에 도착한 뒤 찾아볼 수 있는 동무재, 비밀정원, 은행나무, 청옆골해변을 경기바다 공식 안내 기준으로 정리했습니다.",
    arrivalPort: "풍도 선착장",
    intro: "풍도는 야생화와 해안 풍경으로 알려진 작은 섬입니다. 섬 안 이동과 관람 가능 구간은 계절·기상·현장 여건에 따라 달라질 수 있으므로, 출발 전 공식 안내와 현지 안내를 함께 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 경기바다의 풍도 공식 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "경기바다 풍도 공식 안내",
    officialHref: "https://www.ggbada.co.kr/home/kor/contents.do?menuPos=7",
    ferryGuideHref: "/incheon",
    ferryGuideLabel: "인천 배편 시간표 보기",
    places: [
      {
        name: "동무재",
        category: "산길 · 조망",
        description: "하늘과 맞닿은 길로 소개되는 풍도의 산길입니다. 탐방 전 날씨와 산길 상태를 확인하고, 귀항편을 고려해 여유 있게 이동하세요.",
        mapQuery: "풍도 동무재",
        officialHref: "https://www.ggbada.co.kr/home/kor/contents.do?menuPos=7",
      },
      {
        name: "풍도 비밀정원",
        category: "야생화 · 자연",
        description: "야생화 풍경으로 소개되는 장소입니다. 개화 시기와 탐방 가능 구간은 매년 달라질 수 있으므로 방문일 현장 안내를 우선 확인하세요.",
        mapQuery: "풍도 비밀정원",
        officialHref: "https://www.ggbada.co.kr/home/kor/contents.do?menuPos=7",
      },
      {
        name: "풍도 은행나무",
        category: "고목 · 마을 풍경",
        description: "수령 500년 이상으로 소개되는 풍도의 은행나무입니다. 마을 생활 공간과 인접할 수 있어 조용한 관람과 현장 안내 준수가 필요합니다.",
        mapQuery: "풍도 은행나무",
        officialHref: "https://www.ggbada.co.kr/home/kor/contents.do?menuPos=7",
      },
      {
        name: "청옆골해변",
        category: "해변 · 해안 풍경",
        description: "풍도해전과 관련된 해안으로 소개되는 곳입니다. 해안 접근과 산책은 파고·물때·현장 안전 여건을 확인한 뒤 계획하세요.",
        mapQuery: "풍도 청옆골해변",
        officialHref: "https://www.ggbada.co.kr/home/kor/contents.do?menuPos=7",
      },
    ],
  },
  {
    slug: "jeju-port",
    region: "제주",
    title: "제주항 도착 뒤 둘러볼 곳 — 원도심 4곳",
    description: "제주항 연안여객터미널에 도착한 뒤 찾아볼 수 있는 동문수산시장, 동문재래시장, 제주목관아, 용연·용두암 해안 일대를 제주관광 공식 안내 기준으로 정리했습니다.",
    arrivalPort: "제주항 연안여객터미널",
    intro: "제주행 배편의 도착지는 제주항 연안여객터미널입니다. 장거리 항로 뒤 바로 이동하기 좋은 제주 원도심 중심의 장소를 정리했습니다. 운영 시간과 이동 수단은 수시로 바뀔 수 있으므로 방문 전 공식 안내를 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 제주관광공사 Visit Jeju의 관광지·공식 가이드북 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "Visit Jeju 제주 원도심 공식 안내",
    officialHref: "https://www.visitjeju.net/pdf/Official%20Jeju%20Tourism%20Guidebook_kr.pdf",
    ferryGuideHref: "/jeju",
    ferryGuideLabel: "제주 배편 시간표 보기",
    places: [
      {
        name: "동문수산시장",
        category: "시장 · 먹거리",
        description: "제주항 여객터미널에서 가까운 수산물 전문시장으로 소개됩니다. 점포별 운영 시간과 판매 품목은 현장 또는 공식 안내를 확인하세요.",
        mapQuery: "제주 동문수산시장",
        officialHref: "https://www.visitjeju.net/kr/detail/view?contentsid=CONT_000000000500744&menuId=DOM_000001720003000000",
      },
      {
        name: "동문재래시장",
        category: "전통시장 · 원도심",
        description: "제주 원도심의 대표 전통시장입니다. 시장과 야시장 운영은 점포·계절에 따라 달라질 수 있으므로 방문 전 공식 안내를 확인하세요.",
        mapQuery: "제주 동문재래시장",
        officialHref: "https://www.visitjeju.net/kr/detail/view?contentsid=CONT_000000000500745&menuId=DOM_000001820000000001",
      },
      {
        name: "제주목관아",
        category: "역사 · 문화",
        description: "제주 원도심의 역사 공간으로, 제주항과 동문시장 일대 이동 동선에서 함께 찾아볼 수 있습니다. 관람 가능 시간은 공식 안내를 확인하세요.",
        mapQuery: "제주목관아",
        officialHref: "https://www.visitjeju.net/pdf/Official%20Jeju%20Tourism%20Guidebook_kr.pdf",
      },
      {
        name: "용연·용두암 해안",
        category: "해안 풍경 · 산책",
        description: "제주 원도심 해안 풍경을 볼 수 있는 장소입니다. 해안 산책은 날씨와 파도 등 현장 안전 여건을 확인한 뒤 이동하세요.",
        mapQuery: "제주 용연 용두암",
        officialHref: "https://www.visitjeju.net/pdf/Official%20Jeju%20Tourism%20Guidebook_kr.pdf",
      },
    ],
  },
  {
    slug: "ulleungdo",
    region: "울릉도",
    title: "울릉도 도착 뒤 둘러볼 곳 — 도동·저동 일대 4곳",
    description: "울릉도에 도착한 뒤 찾아볼 수 있는 행남해안산책로, 독도전망대, 촛대바위, 내수전일출전망대를 한국관광공사 안내 기준으로 정리했습니다.",
    arrivalPort: "울릉도 도동·저동·사동항",
    intro: "울릉도는 출발지에 따라 도동·저동·사동 등 서로 다른 항구에 도착할 수 있습니다. 숙소와 관광지 이동 전에 실제 하선 항구를 먼저 확인하세요. 해안 산책과 전망대 이동은 기상·현장 통행 여건에 따라 달라질 수 있습니다.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 한국관광공사 대한민국 구석구석의 울릉도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·통행·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "대한민국 구석구석 울릉도 공식 안내",
    officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=1cb11f9f-21e8-4394-94da-164d9bf60916",
    ferryGuideHref: "/ulleung",
    ferryGuideLabel: "울릉도 배편 시간표 보기",
    places: [
      {
        name: "행남해안산책로",
        category: "해안 산책 · 절경",
        description: "도동에서 행남을 거쳐 저동까지 이어지는 해안 산책 구간으로 소개됩니다. 통행 가능 구간은 파도·기상·정비 상황에 따라 달라질 수 있어 출발 전 확인이 필요합니다.",
        mapQuery: "울릉도 행남해안산책로",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=1cb11f9f-21e8-4394-94da-164d9bf60916",
      },
      {
        name: "독도전망대",
        category: "전망 · 도동 일대",
        description: "도동항과 해안 풍경을 조망할 수 있는 전망 장소로 소개됩니다. 관람 및 케이블카 운영 여부는 날씨와 현장 안내를 확인하세요.",
        mapQuery: "울릉도 독도전망대",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=1cb11f9f-21e8-4394-94da-164d9bf60916",
      },
      {
        name: "촛대바위",
        category: "해안 지형 · 저동",
        description: "저동항 인근의 대표 해안 경관으로 소개됩니다. 실제 하선 항구와 이동 시간을 확인해 귀항편에 무리가 없도록 동선을 잡으세요.",
        mapQuery: "울릉도 촛대바위",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=1cb11f9f-21e8-4394-94da-164d9bf60916",
      },
      {
        name: "내수전일출전망대",
        category: "전망 · 해안 풍경",
        description: "저동항과 죽도·관음도 일대를 조망할 수 있는 전망 장소로 소개됩니다. 날씨와 도로 여건을 확인한 뒤 이동하세요.",
        mapQuery: "울릉도 내수전일출전망대",
        officialHref: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=1cb11f9f-21e8-4394-94da-164d9bf60916",
      },
    ],
  },
  {
    slug: "bigeum-docho",
    region: "비금·도초도",
    title: "비금·도초도 주요 관광지 — 선착장 도착 뒤 확인하는 4곳",
    description: "비금·도초도에 도착한 뒤 찾아볼 수 있는 대동염전, 하트해변, 도초 수국공원, 시목해수욕장을 신안군 안내 기준으로 정리했습니다.",
    arrivalPort: "비금·도초도 선착장",
    intro: "비금도와 도초도는 서남문대교로 연결된 두 섬입니다. 같은 항로에서도 실제 하선 선착장과 섬 안 이동 동선이 달라질 수 있어, 숙소·렌터카·관광 일정을 잡기 전 도착 항구와 귀항편을 함께 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 신안군 문화관광·국가유산 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "신안군 비금·도초도 공식 안내",
    officialHref: "https://cn.shinan.go.kr/home/tour/island/island_01",
    ferryGuideHref: "/mokpo",
    ferryGuideLabel: "목포 배편 시간표 보기",
    places: [
      {
        name: "비금도 대동염전",
        category: "국가등록유산 · 염전 풍경",
        description: "비금 주민들이 조합을 만들어 조성한 천일염전으로 소개되는 국가등록유산입니다. 염전 내부 출입과 관람 가능 구역은 현장 안내를 확인하세요.",
        mapQuery: "비금도 대동염전",
        officialHref: "https://cn.shinan.go.kr/home/www/about/cultural/cultural_03/show/126?page=1",
      },
      {
        name: "하트해변",
        category: "해변 · 해안 풍경",
        description: "비금도의 대표 해변으로 소개되는 장소입니다. 해변 접근과 산책은 날씨·파고·현장 안전 여건을 확인한 뒤 계획하세요.",
        mapQuery: "비금도 하트해변",
        officialHref: "https://cn.shinan.go.kr/home/www/openinfo/participation_07/participation_07_01/show/28938",
      },
      {
        name: "도초 수국공원",
        category: "정원 · 계절 관광",
        description: "폐교 부지에 수국을 테마로 조성된 공원으로 소개됩니다. 개화 시기와 행사·시설 운영은 해마다 달라질 수 있으므로 방문 전 확인하세요.",
        mapQuery: "도초 수국공원",
        officialHref: "https://cn.shinan.go.kr/download/etc1/2016/02.pdf",
      },
      {
        name: "시목해수욕장",
        category: "해변 · 휴식",
        description: "도초도의 해변으로 소개되는 장소입니다. 계절별 해변 이용 가능 여부와 이동 여건은 현장 또는 신안군 안내를 확인하세요.",
        mapQuery: "도초도 시목해수욕장",
        officialHref: "https://cn.shinan.go.kr/download/etc1/2016/02.pdf",
      },
    ],
  },
  {
    slug: "oedaldo",
    region: "외달도",
    title: "외달도 주요 관광지 — 선착장 도착 뒤 확인하는 4곳",
    description: "외달도에 도착한 뒤 찾아볼 수 있는 해수욕장, 해수풀장, 갯벌체험, 해변길을 목포문화관광 공식 안내 기준으로 정리했습니다.",
    arrivalPort: "외달도 선착장",
    intro: "외달도행은 달리도·율도 등을 순회하는 편으로 표시될 수 있습니다. 외달도에 도착한 뒤에는 도보 이동이 가능한 섬이지만, 계절 시설과 해변 체험 운영 여부는 출발 전 확인하세요.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 목포문화관광의 외달도 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "목포문화관광 외달도 공식 안내",
    officialHref: "https://www.mokpo.go.kr/tour/attraction/area?idx=7476&mode=view",
    ferryGuideHref: "/mokpo",
    ferryGuideLabel: "목포 배편 시간표 보기",
    places: [
      {
        name: "외달도 해수욕장",
        category: "해변 · 휴식",
        description: "고운 모래 백사장과 바다 풍경으로 소개되는 외달도의 대표 해변입니다. 해변 이용 가능 기간과 편의시설 운영 여부는 방문일에 확인하세요.",
        mapQuery: "외달도 해수욕장",
        officialHref: "https://www.mokpo.go.kr/tour/attraction/island?idx=7476&mode=view",
      },
      {
        name: "외달도 해수풀장",
        category: "계절 시설 · 물놀이",
        description: "해수욕장 인근의 계절 운영 시설입니다. 개장 기간과 이용 가능 여부는 해마다 달라질 수 있어 목포문화관광 또는 현장 안내를 확인해야 합니다.",
        mapQuery: "외달도 해수풀장",
        officialHref: "https://www.mokpo.go.kr/tour/attraction/area?idx=7476&mode=view",
      },
      {
        name: "외달도 갯벌체험",
        category: "갯벌 · 체험",
        description: "외달도 해변 일대에서 소개되는 체험 활동입니다. 물때와 기상, 체험 운영 여부가 중요하므로 예약·현장 안내를 먼저 확인하세요.",
        mapQuery: "외달도 갯벌체험",
        officialHref: "https://www.mokpo.go.kr/tour/attraction/area?idx=7476&mode=view",
      },
      {
        name: "외달도 해변길·솔머리끝",
        category: "해안 산책 · 조망",
        description: "해변을 따라 걸으며 섬 풍경을 볼 수 있는 동선입니다. 해안 산책은 일몰 전 귀항편과 기상·현장 안전 여건을 고려해 계획하세요.",
        mapQuery: "외달도 솔머리끝",
        officialHref: "https://www.odii.kr/smarttour_web/story/detail?from=iframe&sid=3282&slid=8072&tid=2650&tlid=2778",
      },
    ],
  },
  {
    slug: "jangsan-haui-sinui",
    region: "장산·하의·신의도",
    title: "장산·하의·신의도 주요 관광지 — 섬별로 확인하는 4곳",
    description: "목포에서 연결되는 장산·하의·신의도 항로 이용자를 위해 대성산성, 김대중 대통령 생가, 농민운동기념관, 황성금리해수욕장을 신안군 안내 기준으로 정리했습니다.",
    arrivalPort: "장산·하의·신의도 각 선착장",
    intro: "이 항로는 여러 섬을 경유하거나 편마다 하선 섬이 달라질 수 있습니다. 같은 항로 이름만 보고 이동하지 말고, 시간표의 실제 도착 섬과 선착장을 먼저 확인하세요. 관광지는 섬별로 떨어져 있어 당일 이동 가능 여부도 귀항편 기준으로 판단해야 합니다.",
    sourceNote: "2026-09-07 작성. 관광지 명칭과 소개 범위는 신안군 문화관광·신안군 안내 자료를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 정확한 위치·운영 정보는 연결된 안내와 현지 운영처를 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "신안군 섬 관광 공식 안내",
    officialHref: "https://cn.shinan.go.kr/home/tour/island/island_01",
    ferryGuideHref: "/mokpo",
    ferryGuideLabel: "목포 배편 시간표 보기",
    places: [
      {
        name: "장산도 대성산성 일대",
        category: "역사 · 산 능선",
        description: "장산도의 산줄기와 대성산성 유적으로 알려진 곳입니다. 산길과 유적지 접근 가능 구간은 현장 안내를 확인하고, 하선 섬이 장산도인지 먼저 확인하세요.",
        mapQuery: "장산도 대성산성",
        officialHref: "https://encykorea.aks.ac.kr/Article/E0048512",
      },
      {
        name: "김대중 대통령 생가",
        category: "역사 · 하의도",
        description: "하의도의 대표 역사 공간으로 소개됩니다. 하의도 하선 편인지 확인한 뒤 방문하고, 관람 가능 여부와 이동 정보는 공식 안내를 확인하세요.",
        mapQuery: "하의도 김대중 대통령 생가",
        officialHref: "https://cn.shinan.go.kr/download/etc1/2016/02.pdf",
      },
      {
        name: "하의3도 농민운동기념관",
        category: "역사 · 하의도",
        description: "하의·상태·하태도 농민들의 토지 투쟁사를 기념하는 공간으로 소개됩니다. 관람 전 운영 시간과 위치를 현지 안내에서 확인하세요.",
        mapQuery: "하의3도 농민운동기념관",
        officialHref: "https://cn.shinan.go.kr/download/etc1/2016/02.pdf",
      },
      {
        name: "황성금리해수욕장",
        category: "해변 · 신의도",
        description: "신의도의 해변으로 소개되는 장소입니다. 하선 섬이 신의도인지와 해변 이용 가능 기간·현장 안전 여건을 확인한 뒤 이동하세요.",
        mapQuery: "신의도 황성금리해수욕장",
        officialHref: "https://cn.shinan.go.kr/download/etc1/2016/02.pdf",
      },
    ],
  },
  {
    slug: "seogeocha-gwanmaedo",
    region: "서거차도·관매도",
    title: "서거차도·관매도 해역 안내 — 경유 항로를 이용할 때 확인할 4곳",
    description: "율목·서거차 항로 이용자를 위해 서거차도와 관매도 해변·곰솔 숲, 경유 항로 확인 방법을 진도군 관광문화 공식 안내 기준으로 정리했습니다.",
    arrivalPort: "서거차도·관매도 등 조도면 각 선착장",
    intro: "율목·서거차 편은 여러 섬을 길게 경유하는 생활 항로입니다. 모든 편이 같은 섬에 기항하는 것은 아니며, 여객 요청에 따라 기항 여부가 달라질 수 있습니다. 여행 목적이라면 시간표의 실제 기항지와 하선 가능 여부를 먼저 확인한 뒤 관광지를 정하세요.",
    sourceNote: "2026-09-07 작성. 관광지와 운항 유의사항은 진도군 관광문화의 섬·바다 및 여객선 운항시간표 안내를 바탕으로 정리했습니다. 지도 링크는 장소를 찾기 위한 검색 링크이며, 기항·운항·시설 운영 여부는 출발 전 공식 안내와 현지 운영처에서 확인하세요.",
    updated: "2026-09-07",
    sourceLabel: "진도군 관광문화 조도·관매도 공식 안내",
    officialHref: "https://www.jindo.go.kr/tour/sub.cs?m=81",
    ferryGuideHref: "/mokpo",
    ferryGuideLabel: "목포 배편 시간표 보기",
    places: [
      {
        name: "서거차도 해안과 어촌",
        category: "섬 풍경 · 어촌",
        description: "다도해해상국립공원 안에 있는 서거차도는 어업 전진기지와 낚시 방문지로 알려진 섬입니다. 관광 시설 중심의 섬은 아니므로, 하선 가능 편·숙박·현지 이동 여부를 먼저 확인한 뒤 찾는 편이 좋습니다.",
        mapQuery: "서거차도",
        officialHref: "https://jindo.go.kr/home/board/B0016.cs?act=read&articleId=223&categoryId=0&m=22&pageIndex=1611&searchCondition=&searchKeyword=",
      },
      {
        name: "관매도 해변",
        category: "해변 · 가족 휴식",
        description: "부드러운 모래사장과 얕은 수심, 소나무 숲으로 소개되는 관매도의 대표 해변입니다. 서거차 항로의 경유지로 표시될 수 있으므로 관매도에서 실제로 내릴 수 있는 편인지 먼저 확인하세요.",
        mapQuery: "관매도 해변",
        officialHref: "https://www.jindo.go.kr/tour/tour/info/nature/002.cs?act=view&category=002&infoId=4&m=&pageIndex=1&searchCondition=&searchKeyword=",
      },
      {
        name: "관매도 곰솔 숲과 해변길",
        category: "숲 · 해안 산책",
        description: "관매도 해변 주변의 오래된 곰솔 숲과 해안 풍경은 진도군 관광 안내에서 함께 소개됩니다. 숲길·해변 이동은 일몰 전 귀항편과 기상, 현장 안전 여건을 고려해 계획하세요.",
        mapQuery: "관매도 곰솔 숲",
        officialHref: "https://jindo.go.kr/tour/content/print.cs?m=57&qry=RwM55YMYpaNqZ+E4UbOTChWytMpQ3YuUIAj1clRs2hRXiCvBSw5ZE6yy4H5mxki2r%2FfJBR80HMrsSFUPW46J3Q%3D%3D",
      },
      {
        name: "관매도·서거차 경유 항로",
        category: "여객선 · 일정 계획",
        description: "진도군 공식 시간표에는 관매도·동거차도·서거차도를 잇는 경유 항로가 안내됩니다. 계절·조석·기상에 따라 시간이 달라질 수 있고 사전 요청이 필요한 기항도 있어, 섬 방문 전 최신 시간표를 확인해야 합니다.",
        mapQuery: "서거차도 선착장",
        officialHref: "https://www.jindo.go.kr/tour/sub.cs?m=81",
      },
    ],
  },
]

export function getTourGuide(slug: string): TourGuide | undefined {
  return TOUR_GUIDES.find((guide) => guide.slug === slug)
}
